### ISSUE TITLE
建议使用幕布，这样很不方便的，相信我

### ISSUE THREAD

**Issue by zisheng-ai** [SaekiRaku/yearbook#1]

**Comment by SaekiRaku** [comment]
幕布使用过，不是很满足我的个人需求。

**Comment by zisheng-ai** [comment]
我看你写的了，完全满足呀

**Comment by SaekiRaku** [comment]
> 我看你写的了，完全满足呀

你现在在这个仓库里所看到的只是最终导出的 Markdown 文档，实际上在我的个人电脑上有特定的配置和辅助应用来维护这份日志。目前的配置对我来说其实很方便。

**Comment by SaekiRaku** [comment]
@youngjuning 幕布不符合我的需求的主要原因如下：

1. 幕布是专注结构化信息的，使用户可以整理、检索、归纳零散的信息碎片为结构化的文档。但是我的日志只有一个时间标题和子项目，平均就只有2级结构，而且我也不需要寻找各个项目之间的逻辑关联，它只是一份扁平的日志记录。所以，幕布上再多的功能对我来说也毫无用途。

2. 目前我所使用的 Markdown 编辑器提供了一些 API ，让我可以一个快捷键直接添加今天的日志，日期都是自动生成的。而幕布不支持这样的定制化。虽然幕布的结构管理很给力，但是对于日志这种统一/单一结构的文档，反而需要我手动维护。

3. 我所有的笔记/文字记录应用，有一个最基本的点就是必须是基于或者可导出 Markdown 这种通用结构的。因为一旦某个应用停止维护了，我可以随时把重要的内容转移，并且不需要任何额外的操作和解析就可以导入到另一个应用中。我购买了很多款类似软件，最终停留在了现有的几个产品上。

4. 尽管如此，我对目前的文字软件依然有部分不满意的地方。所以近期打算自己开发。

Thanks any way.

**Comment by zisheng-ai** [comment]
自己研发吗？666
